

seed_data <- tibble(
  topic = c(
    'Exchange Rates',
    'Monetary Policy',
    'Commodity Markets',
    'Financial Markets',
    'Interest Rates',
    'International Economy',
    'Housing',
    'Demand',
    'GDP',
    'Inflation',
    'Credit Market',
    'Labor Market',
    'Fiscal Policy',
    'Supply',
    'Financial Stability',
    'Business Cycle'),
  seedwords = c(
    #Exchange rates
    list(c('currenc', 'foreign currenc', 'euro', 'exchang rate', 'yen',
           'ecb', 'intervent', 'appreci', 'depreci', 'foreign exchang',
           'exchang market', 'valu dollar', 'futur market', 'foreign central bank', 'specul', 
           'exchang valu', 'deterior', 'euro area', 'forward rate',
           'foreign exchang market', 'exchang valu dollar')),
    #Monetary Policy
    list(c('guidanc', 'fed fund', 'asset purchas', 'discount rate', 'polici rate', 
           'rrp', 'repo', 'swap', 'stimulu', 'cut', 
           'rate increas', 'polici action', 'mandat', 'eas', 'target rang',
           'intervent', 'auction', 'monei suppli', 'inflat target', 'full employ', 
           'rate path', 'polici decis', 'taper', 'open market', 'polici rule', 
           'rate chang', 'rais', 'stanc polici', 'price stabil', 'ioer rate', 
           'polici stanc', 'asset sale', 'hike', 'market oper', 
           'appropri polici', 'fund rate target', 'fund rang', 'stanc monetari polici', 'polici tool', 
           'rate target', 'fund rate rang', 'rate basi', 'real fund rate', 'low interest rate', 
           'higher interest rate', 'higher rate', 'lower rate', 'current polici', 'rate rang', 
           'real fund', 'inflat goal', 'transmiss', 'maximum employ', 'natur rate', 
           'polici path', 'threshold', 'higher interest', 'low interest', 'low rate', 
           'transitori', 'target rate', 'polici chang', 'path polici', 'monetari base', 
           'ioer', 'total reserv', 'real feder fund', 'polici assumpt', 'reserv restraint',
           'rate polici','turmoil', 'effect lower bound', 'chang polici','optim polici', 
           'feder fundsrat', 'futur polici', 'polici move', 'polici respons', 'size balanc sheet', 
           'lower interest', 'lower interest rate', 'neutral rate', 'reinvest polici', 'reserv balanc', 
           'monetari aggreg','spillov', 'tradeoff',  'steadi state', 'equilibrium', 
           'tighten', 'offset', 'cap', 'fed fund rate', 'forward guidanc',
           'treasuri secur', 'overnight rrp', 'dual mandat', 'rate hike',
           'repo rate', 'rrp facil', 'asset purchas program', 'fund rate path', 
           'polici accommod', 'accommod polici', 'refinanc', 'mb purchas',
           'term rrp', 'rate cut', 'swap line', 'revers repo',
           'open market oper', 'rrp rate')),
    #Commodity Markets
    list(c('oil price', 'commod', 'energi price', 'food', 'steel', 
           'ga', 'price pressur', 'barrel', 'price index', 'price oil', 
           'price declin', 'crude oil', 'metal', 'higher price', 
           'commod price', 'price increas', 'food price', 'natur ga',
           'gasolin', 'ga price', 'gasolin price')),
    #Financial Markets
    list(c('investor', 'volatil', 'portfolio', 'premium', 'intervent', 
           'equiti price', 'asset price', 'fundament', 'stock price', 'market fund', 
           'equiti market', 'corpor', 'stock market', 'specul', 'bond yield', 
           'bubbl', 'momentum', 'stress', 'fund market', 'market expect',
           'market condit', 'high yield', 'market price', 'market reaction', 'cd',
           'mb', 'turmoil', 'hedg fund', 'arbitrag', 'market develop', 
           'market function', 'spillov', 'upsid risk', 'downsid risk',
           'treasuri secur', 'corpor bond', 'risk premium', 'treasuri yield')),
    #Interest Rates
    list(c( 'coupon', 'bond market', 'yield curv', 'premium', 'market rate', 'real rate', 
            'rate growth', 'real interest rate', 'real interest', 'rate interest', 
            'equilibrium real', 'low interest rate', 'higher interest rate', 'high yield',
            'higher rate', 'lower rate', 'short rate', 'bond yield', 'natur rate', 
            'higher interest', 'low interest', 'low rate', 'long rate',
            'lower interest', 'lower interest rate', 'neutral rate', 
            'nomin interest', 'nomin interest rate', 'term premium',
            'treasuri secur', 'forward rate', 'treasuri yield')),
    #International Economy
    list(c('import', 'japan', 'euro', 'deficit', 'mexico', 'china', 'net export', 'current account',
           'canada', 'war', 'brazil', 'germani', 'greec', 'rest world', 'foreign economi', 'global economi',
           'tariff', 'tension', 'foreign growth', 'surplu', 'market economi', 'rel price', 
           'global growth', 'turmoil', 'itali', 'good servic', 'ship', 'trade partner', 
           'spillov', 'us', 'japanes', 'euro area', 'hous market', 'import price', 'account deficit',
           'current account deficit', 'advanc economi', 'trade deficit', 'industri countri')),
    #Housing
    list(c('home', 'real estat', 'fundament', 'commerci real', 'famili', 'properti', 
           'price index', 'residenti invest', 'estat market', 'bubbl', 'ratio',
           'market price', 'leverag', 'subprim', 'higher price', 'hous price', 
           'price increas', 'commerci real estat', 'mortgag rate', 'mortgag market',
           'singl famili', 'home sale', 'real estat market', 'home price', 'hous start')),
    #Demand
    list(c('consumpt', 'auto', 'sentiment', 'consum spend', 'retail sale', 'consum confid', 
           'wealth effect', 'capit good', 'durabl', 'import', 'net export', 'capit spend',
           'market expect', 'invest spend', 'incom growth', 'dispos incom', 'good servic',
           'person incom', 'demand' , 'import price', 'hous sector', 'capit expenditur',
           'durabl good', 'motor vehicl', 'auto sale', 'consum sentiment', 'household spend')),
    #GDP
    list(c('gnp', 'real gdp growth', 'real growth', 'potenti output', 'output growth', 'trend growth',
           'product growth', 'real activ', 'slow growth', 'growth real', 'real economi', 'moder growth',
           'slower growth', 'slowdown', 'expenditur', 'strong growth', 'rapid growth', 'nomin gdp',
           'potenti growth', 'real output', 'final sale', 'downward', 'real gnp', 'product gain',
           'downward revis', 'nomin gnp', 'upward revis', 'sustain growth', 'econom expans')),
    #Inflation
    list(c('cpi', 'core inflat', 'pce inflat', 'deflat', 'core pce', 'rate inflat', 'inflat target',
           'inflationari pressur', 'price pressur', 'price inflat', 'price level', 'price index', 
           'disinfl', 'pce price', 'inflat risk', 'rate growth',
           'price stabil', 'consum price', 'growth inflat', 'inflat pressur', 
           'headlin inflat', 'inflationari expect', 'inflat compens', 'breakeven', 
           'inflat side', 'higher inflat', 'inflat goal', 'underli inflat', 'momentum',
           'low inflat', 'market expect', 'slowdown', 'price declin', 'transitori', 'peak', 
           'inflat front', 'outlook inflat', 'pressur inflat', 'inflat outlook', 
           'risk inflat', 'lower inflat', 'inflat forecast', 'higher price',
           'inflat project', 'acceler', 'downward' , 'price increas', 'import price',
           'core pce inflat', 'measur inflat', 'core pce price', 'core cpi',
           'inflat number', 'increas inflat', 'cpi inflat', 'downward revis',
           'upward revis')),
    #Credit Markets
    list(c('borrow', 'lend', 'intervent', 'financ', 'financi condit', 'monei suppli', 'monei growth',
           'credit market', 'market rate', 'corpor', 'bank credit', 'credit spread', 'credit condit',
           'monei market', 'short rate', 'momentum', 'stress', 'market condit', 'monetari growth', 
           'default', 'credit card', 'constraint', 'credit risk', 'eas', 'credit crunch', 'subprim',
           'monei fund', 'primari credit', 'credit rate',  'monetari aggreg', 'tighten', 
           'mortgag market', 'monei market fund')),
    #Labor Market
    list(c('labor forc', 'unemploy', 'slack', 'employ growth', 'full employ', 'labor market condit', 
           'job growth', 'employe', 'strike', 'wage growth', 'payrol employ', 'particip rate',
           'tight labor market', 'tight labor', 'nomin wage', 'improv labor', 'labor product',
           'maximum employ', 'natur rate', 'layoff', 'vacanc rate', 'incom growth', 'salari', 
           'minimum',  'nairu', 'person incom', 'market develop', 'tighten', 'wage increas',
           'labor forc particip', 'job gain', 'employ gain', 'forc particip rate',
           'employ report')),
    #Fiscal Policy
    list(c('fiscal polici', 'deficit', 'stimulu', 'cut', 'budget', 'packag', 'law', 'road', 'elect', 
           'legisl', 'reform', 'defens', 'agenc debt', 'surplu', 'sovereign debt', 'minimum',
           'pension', 'fiscal cliff', 'restructur', 'treasuri secur', 'tax cut', 
           'fiscal stimulu')),
    #Supply
    list(c('wage pressur', 'unit labor cost', 'suppli side', 'unit labor', 'labor cost', 'capac util',
           'profit margin', 'wage price', 'structur product', 'manufactur sector', 'profit',
           'auto', 'vehicl', 'tech', 'truck', 'motor', 'supplier', 'labor product', 'layoff',
           'inventori invest', 'tourism', 'suppli shock', 'construct activ', 'ship',
           'energi sector', 'small busi', 'busi contact', 'industri product', 
           'busi invest', 'busi confid', 'busi spend', 'busi sector', 'import price',
           'high tech', 'sector economi', 'resourc slack', 'capit expenditur', 'household busi',
           'wage increas', 'product gain')),
    #Financial Stability
    list(c('bank system', 'commerci bank', 'reserv requir', 'regul', 'excess reserv', 'bubbl',
           'mutual fund', 'risk manag', 'stress', 'banker', 'ratio', 'fund market', 'deposit',
           'credit spread', 'default', 'leverag', 'credit card', 'counterparti', 'cd', 'mb',
           'credit risk', 'total reserv', 'reserv restraint', 'buffer', 'turmoil', 'larg bank',
           'hedg fund', 'credit crunch', 'subprim', 'monei fund', 'size balanc sheet',
           'reserv balanc', 'risk assess', 'balanc risk', 'financi stabil', 'financi stress',
           'financi system', 'mortgag rate', 'financi institut', 'mortgag market',
           'stress test', 'monei market fund', 'financi crisi', 'agenc mb',
           'financi sector')),
    #Business Cycle
    list(c('cycl', 'momentum', 'rebound', 'slowdown', 'downturn', 'shortfal', 'econom recoveri', 
           'layoff', 'fragil', 'transitori', 'peak', 'suppli shock', 'liabil', 'turmoil', 
           'neg effect', 'upsid risk', 'downsid risk', 'output gap', 'busi cycl',
           'upward pressur', 'financi crisi'))
  ))

labels <- seed_data %>% 
  select(theme = topic) %>% 
  mutate(topic = row_number()) %>% 
  select(topic, theme)


